### ISSUE TITLE
无法删除词条

### ISSUE THREAD

**Issue by CabbCat** [BillYang2016/entrylib#1]
在运行一段时间后部分群会出现无法删除词条的现象，提示无法删除TABLE_xx词条表
在重启mirai后之前不能删除的词条会可以删除，但是删除其他词条时仍然报错无法删除
![{PFI E)BA_YXXNU2H7PLGMY](https://user-images.githubusercontent.com/37258131/124687781-29dcca00-df08-11eb-8375-ba8ef78d7a1a.png)

![QBOD1MWT85KVVDB_3JQ)WZY](https://user-images.githubusercontent.com/37258131/124687838-51339700-df08-11eb-99ac-2d4002157e5f.png)
![W% NUKN85F51(@9UFT_G6 8](https://user-images.githubusercontent.com/37258131/124687860-601a4980-df08-11eb-93c6-a5de5e8967ad.png)

**Comment by CabbCat** [comment]
在删除数据库重新编辑之后仍然会出错 更新失败的报错是无法创建新表
![KN9IFX8AG)16WL1B_1X9NIH](https://user-images.githubusercontent.com/37258131/124689527-3e6e9180-df0b-11eb-99d3-4b9c1099f0cd.jpg)

**Comment by BillYang2016** [comment]
较为棘手的bug，需要时间检查

**Comment by BillYang2016** [comment]
已在 [1.0.2-M1](https://github.com/BillYang2016/entrylib/releases/tag/1.0.2-M1) 中尝试修复，烦请检查修复情况，由于更新了表删除逻辑因此可能需要重新检查配置数据库（最方便的是删除重来），如果仍有问题请重开issue并发送SQLException详情。

**Comment by BillYang2016** [comment]
在 [1.0.2-M2](https://github.com/BillYang2016/entrylib/releases/tag/1.0.2-M2) 中基本完成修复

**Comment by CabbCat** [comment]
> 在 [1.0.2-M2](https://github.com/BillYang2016/entrylib/releases/tag/1.0.2-M2) 中基本完成修复

感谢大佬修复，但是我这边console自动更新了2.7M2，好像不在支持的版本里，希望大佬有空的时候能做一下适配orz

**Comment by BillYang2016** [comment]
> > 在 [1.0.2-M2](https://github.com/BillYang2016/entrylib/releases/tag/1.0.2-M2) 中基本完成修复
> 
> 感谢大佬修复，但是我这边console自动更新了2.7M2，好像不在支持的版本里，希望大佬有空的时候能做一下适配orz

2.7M2 仍是适用版本，稍后更新一下列表🙂
