### ISSUE TITLE
导入表情乱码

### ISSUE THREAD

**Issue by liuqianpan2008** [BillYang2016/entrylib#10]
entry-package.json：https://paste.ubuntu.com/p/yYVcvDqr5s/
ps：催更

**Comment by liuqianpan2008** [comment]
![ETO@V_B_@95WCFDKKR5KOGW.png](https://img13.360buyimg.com/ddimg/jfs/t1/195611/11/16016/191446/6105102bEea5507b7/c73cf37898105544.png)
![ZMTVFH3ARK0JLSZJ7IITCKQ.png](https://img11.360buyimg.com/ddimg/jfs/t1/195631/37/15967/105977/6105102aE1c5f3c0a/64ea13ea32d0bb10.png)
![_~WNQ1__1AY80_EUTKLUDYA.png](https://img14.360buyimg.com/ddimg/jfs/t1/189920/23/15899/14015/6105102aE98feadc6/ef89ec28d83708c9.png)
![__N3J4__D45UY3_@CZ_RC_G.png](https://img11.360buyimg.com/ddimg/jfs/t1/199317/38/697/11400/6105102aEd0d39157/4b6171e86349a52a.png)
补图

**Comment by BillYang2016** [comment]
确认是由于json格式化器造成的问题，已修复，请等待新版本打包
