### ISSUE TITLE
你好 我该如何去让他同时读取一段话中的多个关键词

### ISSUE THREAD

**Issue by fkyah3** [BillYang2016/entrylib#11]
如 我要怎么安装1.16.5的forge服务端啊
我想提取其中的3个关键字 安装 forge 服务端 当他们同时在一句话时触发

**Comment by BillYang2016** [comment]
请使用正则表达式：`安装.*forge.*服务端`
具体指令：`学习#安装.*forge.*服务端#这里是回复内容#正则`

需要注意的是，关键词的顺序会对匹配结果造成影响
