### ISSUE TITLE
希望能够增加全局词库、跨群添加词条、跨群开启词库开关功能。

### ISSUE THREAD

**Issue by WINE92** [BillYang2016/entrylib#13]
**需求描述 Descibe the feature**  

> 全局词库

全局词库默认对Bot所在的全部群生效，该词库只能由Bot作者进行编辑(增加or删除)，并且希望不在常规群内的[全部]指令内显示，能够通过另外的指令进行显示(或是直接在本地进行修改)。

> 跨群添加词条、跨群开启词库开关

跨群添加对应的群内词条、开启词库开关默认只能由Bot作者进行操作，可以通过指令前缀增加输入QQ群号等方式开启(或许)。

“Bot作者”的定义: emmm就是在本地数据目录内 admin.json 内输入的QQ号。`

**这是否是一个突破性变化？Is this a breaking changes?**  
- [Maybe] 

**附加内容 Additional context**  
感谢dalao的插件，非常实用~ 希望能在百忙之中对这些功能新建文件夹(bushi)。

**Comment by BillYang2016** [comment]
> 增加全局词库、跨群添加词条

群分组功能可以实现该功能  
如果您是指一群多词库，这可能是一个有参考性的建议，但实现起来可能比较复杂

> 跨群开启词库开关

这可能带来的负面影响比较大

> 词库只能由 Bot 作者进行编辑(增加or删除)

目前没有区分群主、管理员和 Admin 权限，这是一个有参考性的建议

**希望楼主能够再次确认一下需求，以保证插件继续拥有清晰完备的逻辑体系**

**Comment by BillYang2016** [comment]
1. bug已于以前版本修复
2. 认为必要性不大，搁置
3. 已在1.2.1版本加入，合并至1.3.1
