### ISSUE TITLE
启动MC时遇到整理数据库错误 [SQLITE_ERROR] SQL error or missing database

### ISSUE THREAD

**Issue by soaarp** [BillYang2016/entrylib#14]
> 23:41:15 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
> 23:41:16 [INFO] Verifying "net.mamoe:mirai-console" v2.8.0-M1
>   23:41:16 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.8.0-M1
>   23:41:16 [INFO] Verifying "net.mamoe:mirai-core-all" v2.8.0-M1
>   23:41:17 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
>   23:41:17 [INFO] Verifying "net.mamoe:chat-command" v0.5.1
>   23:41:17 [WARN] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-RC. Current version is 2.8.0-M1
> 2021-10-10 23:41:19 I/main: Starting mirai-console...
> 2021-10-10 23:41:19 I/main: Backend: version 2.8.0-M1, built on 2021-09-22 17:49:01.
> 2021-10-10 23:41:19 I/main: Frontend Terminal: version 2.8.0-M1, provided by Mamoe Technologies
> 2021-10-10 23:41:19 I/main: Welcome to visit https://mirai.mamoe.net/
> 2021-10-10 23:41:19 I/plugin: Successfully loaded plugin AntiLightappShare v0.13.6
> 2021-10-10 23:41:19 I/plugin: Successfully loaded plugin Chat Command v0.5.0
> 2021-10-10 23:41:19 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
> 2021-10-10 23:41:19 I/plugin: Successfully loaded plugin EntryLib v1.1.1
> 2021-10-10 23:41:19 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
> 2021-10-10 23:41:19 I/AntiLightappShare: 反小程序分享插件载入
> 2021-10-10 23:41:19 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
> 2021-10-10 23:41:19 I/EntryLib: 配置文件目录：E:\Downloads\data\EntryLib
> 2021-10-10 23:41:19 I/EntryLib: 开始升级数据库版本
> 2021-10-10 23:41:19 I/EntryLib: 数据库xxxxxxx.db已为最新版本！
> 2021-10-10 23:41:20 I/EntryLib: 词条插件已加载完成！
> 2021-10-10 23:41:20 I/main: 4 plugin(s) enabled.
> 2021-10-10 23:41:20 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
> 2021-10-10 23:41:20 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
> 2021-10-10 23:41:20 I/main: Auto-login xxxxxxx
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
> 2021-10-10 23:41:21 I/Bot.xxxxxxx: Loaded account secrets from local cache.
> 2021-10-10 23:41:21 I/Bot.xxxxxxx: Saved account secrets to local cache for fast login.
> 2021-10-10 23:41:21 I/Bot.xxxxxxx: Login successful.
> 2021-10-10 23:41:21 V/Bot.xxxxxxx: Event: BotOnlineEvent(bot=Bot(xxxxxxx))
> 2021-10-10 23:41:21 I/Bot.xxxxxxx: Bot login successful.
> 2021-10-10 23:41:21 I/main: mirai-console started successfully.
> 2021-10-10 23:41:25 I/EntryLib: 数据库整理器开始执行整理任务
> 2021-10-10 23:41:25 I/EntryLib: 开始整理数据库xxxxxxx.db
> 2021-10-10 23:41:25 E/EntryLib: 无法创建新表TABLE_2，五秒后重试！（1/5）
> 2021-10-10 23:41:25 W/stderr: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table TABLE_2 already exists)
> 2021-10-10 23:41:25 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1012)
> 2021-10-10 23:41:25 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1024)
> 2021-10-10 23:41:25 W/stderr:   at org.sqlite.core.DB.throwex(DB.java:989)
> 2021-10-10 23:41:25 W/stderr:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
> 2021-10-10 23:41:25 W/stderr:   at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
> 2021-10-10 23:41:25 W/stderr:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
> 2021-10-10 23:41:25 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.rearrange(DatabaseAutoArranger.java:227)
> 2021-10-10 23:41:25 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.run(DatabaseAutoArranger.java:392)
> 2021-10-10 23:41:25 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Unknown Source)
> 2021-10-10 23:41:25 W/stderr:   at java.base/java.util.TimerThread.run(Unknown Source)
> 2021-10-10 23:41:30 E/EntryLib: 无法创建新表TABLE_2，五秒后重试！（2/5）
> 2021-10-10 23:41:30 W/stderr: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table TABLE_2 already exists)
> 2021-10-10 23:41:30 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1012)
> 2021-10-10 23:41:30 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1024)
> 2021-10-10 23:41:30 W/stderr:   at org.sqlite.core.DB.throwex(DB.java:989)
> 2021-10-10 23:41:30 W/stderr:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
> 2021-10-10 23:41:30 W/stderr:   at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
> 2021-10-10 23:41:30 W/stderr:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
> 2021-10-10 23:41:30 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.rearrange(DatabaseAutoArranger.java:227)
> 2021-10-10 23:41:30 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.run(DatabaseAutoArranger.java:392)
> 2021-10-10 23:41:30 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Unknown Source)
> 2021-10-10 23:41:30 W/stderr:   at java.base/java.util.TimerThread.run(Unknown Source)
> 2021-10-10 23:41:35 E/EntryLib: 无法创建新表TABLE_2，五秒后重试！（3/5）
> 2021-10-10 23:41:35 W/stderr: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table TABLE_2 already exists)
> 2021-10-10 23:41:35 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1012)
> 2021-10-10 23:41:35 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1024)
> 2021-10-10 23:41:35 W/stderr:   at org.sqlite.core.DB.throwex(DB.java:989)
> 2021-10-10 23:41:35 W/stderr:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
> 2021-10-10 23:41:35 W/stderr:   at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
> 2021-10-10 23:41:35 W/stderr:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
> 2021-10-10 23:41:35 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.rearrange(DatabaseAutoArranger.java:227)
> 2021-10-10 23:41:35 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.run(DatabaseAutoArranger.java:392)
> 2021-10-10 23:41:35 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Unknown Source)
> 2021-10-10 23:41:35 W/stderr:   at java.base/java.util.TimerThread.run(Unknown Source)
> 2021-10-10 23:41:40 E/EntryLib: 无法创建新表TABLE_2，五秒后重试！（4/5）
> 2021-10-10 23:41:40 W/stderr: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table TABLE_2 already exists)
> 2021-10-10 23:41:40 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1012)
> 2021-10-10 23:41:40 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1024)
> 2021-10-10 23:41:40 W/stderr:   at org.sqlite.core.DB.throwex(DB.java:989)
> 2021-10-10 23:41:40 W/stderr:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
> 2021-10-10 23:41:40 W/stderr:   at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
> 2021-10-10 23:41:40 W/stderr:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
> 2021-10-10 23:41:40 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.rearrange(DatabaseAutoArranger.java:227)
> 2021-10-10 23:41:40 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.run(DatabaseAutoArranger.java:392)
> 2021-10-10 23:41:40 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Unknown Source)
> 2021-10-10 23:41:40 W/stderr:   at java.base/java.util.TimerThread.run(Unknown Source)
> 2021-10-10 23:41:45 E/EntryLib: 无法创建新表TABLE_2，五秒后重试！（5/5）
> 2021-10-10 23:41:45 W/stderr: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table TABLE_2 already exists)
> 2021-10-10 23:41:45 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1012)
> 2021-10-10 23:41:45 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1024)
> 2021-10-10 23:41:45 W/stderr:   at org.sqlite.core.DB.throwex(DB.java:989)
> 2021-10-10 23:41:45 W/stderr:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
> 2021-10-10 23:41:45 W/stderr:   at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
> 2021-10-10 23:41:45 W/stderr:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
> 2021-10-10 23:41:45 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.rearrange(DatabaseAutoArranger.java:227)
> 2021-10-10 23:41:45 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.run(DatabaseAutoArranger.java:392)
> 2021-10-10 23:41:45 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Unknown Source)
> 2021-10-10 23:41:45 W/stderr:   at java.base/java.util.TimerThread.run(Unknown Source)
> 2021-10-10 23:41:50 E/EntryLib: 无法完成xxxxx.db数据库整理工作，即将退出！
> 2021-10-10 23:41:50 I/EntryLib: 数据库整理器已完成所有整理任务
> 2021-10-10 23:41:50 I/EntryLib: 数据库整理器已清理未使用的图片缓存：总计0个图片

**Comment by BillYang2016** [comment]
注意看[额外说明](https://github.com/BillYang2016/entrylib#%E9%A2%9D%E5%A4%96%E8%AF%B4%E6%98%8E)
