### ISSUE TITLE
希望词条库的导入导出功能能够增加对于群分组数据库的支持

### ISSUE THREAD

**Issue by byx2020** [BillYang2016/entrylib#16]
![image](https://user-images.githubusercontent.com/58938653/139228273-decf185b-1a88-4e57-94f7-4b7841ccd32f.png)
导出和导入功能的群号输入框，目前不论是填写分组名还是群分组里面任意一个群的群号，都无法导出或导入词条数据。

另外，学习词条插件和词条库插件的导出数据格式差异有一些大，我最初本来想用正则替换统一格式的，但看了半天都没有什么头绪，不知道大佬有没有什么好的建议……
![image](https://user-images.githubusercontent.com/58938653/139231235-565b3286-6d42-4dde-9427-f32aa28829d7.png)

**Comment by BillYang2016** [comment]
第一条有道理，可以加，但是有点懒可能会拖
第二条不做，学习词条已经不维护了，因此不考虑兼容性问题

**Comment by BillYang2016** [comment]
已在[1.1.3](https://github.com/BillYang2016/entrylib/releases/tag/1.1.3)版本中加入，填写分组名即可。
