### ISSUE TITLE
在2.9.0-RC2中移动数据目录失败

### ISSUE THREAD

**Issue by Sirayuki-zh** [BillYang2016/entrylib#17]
![image](https://user-images.githubusercontent.com/49672605/146714046-dea8bdc5-e1ae-4cfa-9001-a060e769ac01.png)

**Comment by BillYang2016** [comment]
尝试手动移动一下？

**Comment by Z233** [comment]
https://github.com/Z233/entrylib/commit/223627d80f7bbab97cb455f4b791142e740390a2
我在我的 fork 里修复了这个问题

**Comment by Sirayuki-zh** [comment]
> 

手动移原地又会出现，才跑来提的issues（

**Comment by BillYang2016** [comment]
> [Z233@223627d](https://github.com/Z233/entrylib/commit/223627d80f7bbab97cb455f4b791142e740390a2) 我在我的 fork 里修复了这个问题

欢迎往这边提交一个PR，：）

**Comment by BillYang2016** [comment]
已在 #18 中解决，并合并至 [1.1.2](https://github.com/BillYang2016/entrylib/releases/tag/1.1.2)
