### ISSUE TITLE
直接回复答案及可选at模式

### ISSUE THREAD

**Issue by LemonPAKA** [BillYang2016/entrylib#23]
**需求描述 Descibe the feature**  
可选在回复关键词的时候不进行复述关键词所在句子，而是直接回复答案，另外建议就是艾特也设置为可选

**这是否是一个突破性变化？Is this a breaking changes?**  
- [ ] 请选中本复选框表示这是一个突破性变化

**附加内容 Additional context**  
您可以在这里添加任何内容

**Comment by soaarp** [comment]
output.json里面view部分的reply这样改一下，还有回复模式改成2
`  "view":
  {
    "exist":"未找到 $1 相关的词条！",
    "reject":"$1 是重要指令或系统保留字段，拒绝对其进行访问！",
    "permission":"权限不足，无法使用！",
    "reply":"$2",
    "error":"查询 $1 时出错啦！"
  },
`

**Comment by BillYang2016** [comment]
如楼上所言，另可见：https://github.com/BillYang2016/entrylib/issues/4#issuecomment-889046165
