### ISSUE TITLE
[BUG]后台显示发送信息到群聊，但群聊中无任何反应

### ISSUE THREAD

**Issue by biobirds** [BillYang2016/entrylib#25]
![20220222095926](https://user-images.githubusercontent.com/32745555/155049350-71e88865-2203-4ba3-9aee-3de8c6588cd4.png)
![image](https://user-images.githubusercontent.com/32745555/155049370-e5691054-c737-4a51-8d3b-aaaf1b67d35c.png)
后台显示发送信息到群聊，但群聊中无任何反应
![image](https://user-images.githubusercontent.com/32745555/155049393-cb25ad0a-986b-407c-9465-073e99e33e71.png)
![image](https://user-images.githubusercontent.com/32745555/155049409-9715390b-2394-46e5-9829-6c35d9d22d5b.png)
配置文件已确认无问题

**Comment by BillYang2016** [comment]
相似问题：#8，#15
需要更多信息：
- 所有消息都发不出来吗？
- 其他插件可以正常使用吗？
- 请提供更多后台信息，目前提供的后台几乎没有可用信息

**Comment by biobirds** [comment]
> 相似问题：#8，#15 需要更多信息：
> 
> * 所有消息都发不出来吗？
> * 其他插件可以正常使用吗？
> * 请提供更多后台信息，目前提供的后台几乎没有可用信息

已经解决了，谢谢回复。腾讯风控问题，手机登录下解除就行了。
