### ISSUE TITLE
无图形 Linux 界面下的运行问题

### ISSUE THREAD

**Issue by Ag-elf** [BillYang2016/entrylib#3]
在无图形的 Linux 终端环境下直接使用或会产生以下错误：
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
希望可以增加无界面的启动方式。

可以使用的临时修复方法：
```shell
sudo apt-get install Xvfb
Xvfb :90 -ac 2>/dev/null &
export DISPLAY=:90
```

**Comment by BillYang2016** [comment]
已在 [41927be](https://github.com/BillYang2016/entrylib/commit/41927bea957acaab9fe8602f67604b5e03cdaf96) 中添加图形环境检测，感谢反馈
