### ISSUE TITLE
请问如何才能让关键字触发的时候bot自动回复？

### ISSUE THREAD

**Issue by sakurakyoko10** [BillYang2016/entrylib#4]
我把“view-mode”修改为1后也没有解决，把reply-mode改成1仍然不回复

**Comment by unlimitwhitenight** [comment]
得用模糊或者正则吧，但是好像并没有生效，没有触发关键字直接回复，试了很久都没有成功，必须要全都是精确回复

**Comment by Ag-elf** [comment]
```shell
# My settings
reply-mode: 0
view-mode: 1
default-switch: 1
```
1. 应该只有在群组会回复
2. 应该需要确认群组是否有权限
3. 应该需要保证词条已经入库
4. mcl 是否有报错 ？

**Comment by BillYang2016** [comment]
> 得用模糊或者正则吧，但是好像并没有生效，没有触发关键字直接回复，试了很久都没有成功，必须要全都是精确回复

`view-mode`调整为`1`后使用模糊方式学习。  
请重试一下，若仍有相同问题请提供一下详细信息或复现方案

**Comment by unlimitwhitenight** [comment]
> > 得用模糊或者正则吧，但是好像并没有生效，没有触发关键字直接回复，试了很久都没有成功，必须要全都是精确回复
> 
> `view-mode`调整为`1`后使用模糊方式学习。
> 请重试一下，若仍有相同问题请提供一下详细信息或复现方案

重新试了一下，模糊能用，但是正则好像用不了，有没有例子说明一下比如 /正则表达式/ 之类的

**Comment by BillYang2016** [comment]
> 重新试了一下，模糊能用，但是正则好像用不了，有没有例子说明一下比如 /正则表达式/ 之类的

将正则匹配模式串作为词条名，将回复内容作为词条内容，我稍后添加例子放在 README 中

**Comment by BillYang2016** [comment]
> 重新试了一下，模糊能用，但是正则好像用不了，有没有例子说明一下比如 /正则表达式/ 之类的

[已添加示例](https://github.com/BillYang2016/entrylib#%E5%AD%A6%E4%B9%A0%E8%AF%8D%E6%9D%A1%E5%90%8D%E8%AF%8D%E6%9D%A1%E5%86%85%E5%AE%B9%E5%9B%9E%E5%A4%8D%E9%A1%B9%E5%8C%B9%E9%85%8D%E6%96%B9%E5%BC%8F)

**Comment by BillYang2016** [comment]
> 我把“view-mode”修改为1后也没有解决，把reply-mode改成1仍然不回复

@sakurakyoko10 请问问题是否已解决

**Comment by BillYang2016** [comment]
另，若只需要回复，推荐修改`output.json`配置：
```diff
"view":{
-  "reply":"$1 的内容如下：\n--------\n$2"
+  "reply":"$2"
}
```

本issue将关闭
