### ISSUE TITLE
图片跟表情发送失效

### ISSUE THREAD

**Issue by unlimitwhitenight** [BillYang2016/entrylib#5]
![20210727-083547](https://user-images.githubusercontent.com/14921482/127076714-6acf10d5-0cde-4444-a357-4ec8643a5044.jpg)
![QQ截图20210727083755](https://user-images.githubusercontent.com/14921482/127076742-c2859ffd-1261-4fb4-b16e-bb28fb8f458d.png)
在机器人的路径下的image里有看到图片被保存，但是发送的时候出了问题。并且表情的保存实际上是文字，有些设备看上去并不是表情

**Comment by BillYang2016** [comment]
这看上去是一个bug，也复现成功了，插件没有对表情码进行适配

---
但images不应该保存这个表情，是不是哪里弄错了（

**Comment by BillYang2016** [comment]
确认问题是“Mirai码支持未适配”，将在未来版本进行更新

**Comment by unlimitwhitenight** [comment]
> 确认问题是“Mirai码支持未适配”，将在未来版本进行更新

是bug啊，我试了一下有的能发，有的需要发很多次，我还以为是因为是arm64或者性能问题

**Comment by BillYang2016** [comment]
> > 确认问题是“Mirai码支持未适配”，将在未来版本进行更新
> 
> 是bug啊，我试了一下有的能发，有的需要发很多次，我还以为是因为是arm64或者性能问题

目前只对 Image 的 Mirai 码进行了适配，之后我会把目前支持的 Mirai 码放进 README 中

**Comment by BillYang2016** [comment]
已在 [5f38d13](https://github.com/BillYang2016/entrylib/commit/5f38d1346727c274e6b36cbffd76401007270d6d) 中加入表情适配，请等待新版本打包发布
