### ISSUE TITLE
关于多词条匹配的不确定性问题

### ISSUE THREAD

**Issue by Ag-elf** [BillYang2016/entrylib#6]
![QQ截图20210728095600](https://user-images.githubusercontent.com/16291478/127253182-2b010286-753d-4993-bf1d-c40dedf3ad0a.png)

当存在多个合法匹配时，或有可能出现行为不确定的情况。

请问能否详述下具体的匹配优先级，或者是否有办法可以手动配置匹配的优先级？

* 似乎词条的添加顺序会影响匹配顺序

**Comment by BillYang2016** [comment]
确实如此，现在的顺序是：
1. 检测是否有存在的精确匹配，若存在返回最小编号
2. 检测是否有存在的模糊匹配，若存在返回最小编号
3. 检测是否有存在的正则匹配，若存在返回最小编号

-----

关于手动调整优先级，已经在计划中了

**Comment by Ag-elf** [comment]
嗯，了解了，可以考虑将优先级说明先暂时加入文档，以免造成迷惑。
