### ISSUE TITLE
数据库的结构的一些建议

### ISSUE THREAD

**Issue by unlimitwhitenight** [BillYang2016/entrylib#7]
最近有遇到过无法创建新表的情况，所以想问一下数据库能否改成以下结构
主表__MAIN_TABLE:
       tid(匹配词id),
       title(匹配词内容),
       match_mode(匹配模式)

词表_SEARCH_TABLE:
       tid_id(匹配词id跟结果词id拼接，用于主键),
       tid(匹配词id),
       id(结果词id),
       content(结果词内容),
       ts(时间)

**Comment by BillYang2016** [comment]
之前考虑过引入外键，但是这好像只是增加了空间负担，对于词条数据库来说仅需要索引而不需要连接。

无法创建新表的原因一般是因为数据库被临时占用，sqlite没有写锁并发性较差（与数据库结构关系不大），且不会长时间出现本情况。
您可以提供更详细的信息（如复现步骤、控制台info等），以便于定位问题原因进行优化
